server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 32
  http2:
    enabled: true
  error:
    include-exception: true
    whitelabel:
      enabled: false
  servlet:
    jsp:
      registered: false

spring:
  application:
    name: "spring-panic-button"
  jackson:
    default-property-inclusion: non_absent
    time-zone: "UTC" # Always send and receive UTC dates by default
    property-naming-strategy: SNAKE_CASE
  mvc:
    format:
      date: iso # Always send and receive UTC dates by default (URL params)
  datasource:
    url: "jdbc:postgresql://localhost:15432/spb"
    username: "spb"
    password: "spb.123"
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never
  flyway:
    enabled: false

panic-button:
  security:
    enabled: true
