spring:
  application:
    name: spring-panic-button
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never
  flyway:
    enabled: false