spring:
  application:
    name: spring-panic-button
  datasource:
    url: jdbc:postgresql://localhost:15432/spb
    username: "spb"
    password: "spb.123"
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never
  flyway:
    enabled: false
