DROP TABLE IF EXISTS panic_status;

CREATE TABLE panic_status
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    general_status  VARCHAR(64)                              NOT NULL,
    detailed_status JSONB,
    dt_status       TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    CONSTRAINT PK_panic_status PRIMARY KEY (id)
);

CREATE INDEX IDX_panic_status___dt_status ON panic_status (dt_status);

INSERT INTO panic_status
VALUES (1, 'OK', NULL, NOW());
