DROP TABLE IF EXISTS referers_enum;
CREATE TABLE referers_enum
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(32)                              NOT NULL,
    score BIGINT DEFAULT 0                         NOT NULL,
    CONSTRAINT PK_REFERERS_ENUM PRIMARY KEY (id),
    CONSTRAINT UNIQUE_REFERERS_ENUM_NAME UNIQUE (name)
);

INSERT INTO referers_enum VALUES (3533, 'Google', 71);
INSERT INTO referers_enum VALUES (508, 'Facebook', 781);
INSERT INTO referers_enum VALUES (3618, 'Twitter', 30);
INSERT INTO referers_enum VALUES (30, 'Unknown', 2114);
INSERT INTO referers_enum VALUES (48, 'Telegram', 585);
INSERT INTO referers_enum VALUES (63, 'Instagram', 1911);
INSERT INTO referers_enum VALUES (1, 'Direct', 45904);
INSERT INTO referers_enum VALUES (5968, 'LinkedIn', 1);
INSERT INTO referers_enum VALUES (41, 'Gmail', 19);

DROP TABLE IF EXISTS mediums_enum;
CREATE TABLE mediums_enum
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(32)                              NOT NULL,
    score BIGINT DEFAULT 0                         NOT NULL,
    CONSTRAINT PK_MEDIUMS_ENUM PRIMARY KEY (id),
    CONSTRAINT UNIQUE_MEDIUMS_ENUM_NAME UNIQUE (name)
);

INSERT INTO mediums_enum VALUES (3533, 'search', 71);
INSERT INTO mediums_enum VALUES (30, 'unknown', 2114);
INSERT INTO mediums_enum VALUES (41, 'apps', 603);
INSERT INTO mediums_enum VALUES (63, 'social', 2723);
INSERT INTO mediums_enum VALUES (1, 'direct', 45904);
INSERT INTO mediums_enum VALUES (411, 'email', 1);

DROP TABLE IF EXISTS devices_enum;
CREATE TABLE devices_enum
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(32)                              NOT NULL,
    score BIGINT DEFAULT 0                         NOT NULL,
    CONSTRAINT PK_DEVICES_ENUM PRIMARY KEY (id),
    CONSTRAINT UNIQUE_DEVICES_ENUM_NAME UNIQUE (name)
);

INSERT INTO devices_enum VALUES (351, 'Embedded', 3);
INSERT INTO devices_enum VALUES (149, 'Hacker', 59);
INSERT INTO devices_enum VALUES (42500, 'Game Console', 3);
INSERT INTO devices_enum VALUES (8, 'Cloud', 10921);
INSERT INTO devices_enum VALUES (153, 'Unknown', 526);
INSERT INTO devices_enum VALUES (6, 'Mobile', 29570);
INSERT INTO devices_enum VALUES (1, 'Desktop', 5287);
