DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid         UUID                                    NOT NULL,
    username    VARCHAR(64)                             NOT NULL,
    provider    VARCHAR(16)                             NOT NULL,
    provider_id VARCHAR(64)                             NOT NULL,
    image_url   VARCHAR(256),
    first_name  VARCHAR(64)                             NOT NULL,
    last_name   VARCHAR(64),
    active      BOOLEAN DEFAULT FALSE                   NOT NULL,
    premium     BOOLEAN DEFAULT FALSE                   NOT NULL,
    adm         BOOLEAN DEFAULT FALSE                   NOT NULL,
    created     TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated     TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UNIQUE_USER_UID UNIQUE (uid),
    CONSTRAINT UNIQUE_USER_PROVIDER___PROVIDER_ID UNIQUE (provider, provider_id)
);

INSERT INTO users (uid, username, provider, provider_id, image_url, first_name, last_name, active, premium, adm,
                   created, updated)
VALUES (GEN_RANDOM_UUID(), 'rafael.lins777@gmail.com', 'google', '110783073489321022611',
        'https://lh3.googleusercontent.com/a-/AOh14GjSGw_vjnIkylcFZVk_FNufUa9ZKn2ypthqWgweSg=s96-c', 'Rafael', 'Lins',
        'true', 'true', 'true', NOW(), NOW());
